In [3]:
#1.

import numpy as np
arr = np.arange(2, 50, 3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [4]:
#2.

import numpy as np
list1=list(map(int,input("enter 5 values").split()))[:5]
list2=list(map(int,input("enter 5 values").split()))[:5]
a = np.array(list1)
b = np.array(list2)
c=np.concatenate((a, b), axis=0)
print(c)
print(np.sort(c))

enter 5 values2 3 4 5 6 
enter 5 values4 3 5 6 7 8
[2 3 4 5 6 4 3 5 6 7]
[2 3 3 4 4 5 5 6 6 7]


In [5]:
#3.

a = np.arange(3)
print(a)
a1 = np.arange(12).reshape((3, 4))
print(a1)
print(a.ndim)
print(a1.ndim)
print(a.size)

[0 1 2]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
1
2
3


In [6]:
#4.

import numpy as np
arr = np.arange(1*1).reshape(1, 1) 
print(arr.shape) 
arr_2D = arr[np.newaxis, ..., np.newaxis, np.newaxis] 
  
print(arr_2D.shape)

x = np.zeros((3, 4)) 
y = np.expand_dims(x, axis=1).shape 
print(y) 

(1, 1)
(1, 1, 1, 1, 1)
(3, 1, 4)


In [7]:
#5.

## Horitzontal Stack
import numpy as np
m = np.array([1,2,3,4])
n = np.array([5,6,7,8])

print('Horizontal Append:', np.hstack((m, n)))

## Vertical Stack
import numpy as np
s = np.array([1,2,3,4])
t = np.array([5,6,7,8])

print('Vertical Append:', np.vstack((s, t)))

Horizontal Append: [1 2 3 4 5 6 7 8]
Vertical Append: [[1 2 3 4]
 [5 6 7 8]]


In [8]:
import numpy as np
a = np.array( [20,10,20,10,20,30,20,30, 30,50,40,40,50,100,100] )
print("Original array:")
print(a)
unique_elements, counts_elements = np.unique(a, return_counts=True)
print("Frequency of unique values of the said array:")
print(np.asarray((unique_elements, counts_elements)))

Original array:
[ 20  10  20  10  20  30  20  30  30  50  40  40  50 100 100]
Frequency of unique values of the said array:
[[ 10  20  30  40  50 100]
 [  2   4   3   2   2   2]]
